/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"

struct getattr_IDL *
getattr_1000_svc(struct getattr_IDL *argp, struct svc_req *rqstp)
{
	static struct getattr_IDL  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
mkdir_1000_svc(mkdir_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rmdir_1000_svc(rmdir_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
open_1000_svc(open_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct read_ret_IDL *
read_1000_svc(read_IDL *argp, struct svc_req *rqstp)
{
	static struct read_ret_IDL  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct write_IDL *
write_1000_svc(write_IDL *argp, struct svc_req *rqstp)
{
	static struct write_IDL  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct opendir_ret_IDL *
opendir_1000_svc(opendir_IDL *argp, struct svc_req *rqstp)
{
	static struct opendir_ret_IDL  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct readdir_ret_IDL *
readdir_1000_svc(readdir_IDL *argp, struct svc_req *rqstp)
{
	static struct readdir_ret_IDL  result;

	/*
	 * insert server code here
	 */

	return &result;
}

void *
hellotest_1000_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

int *
access_1000_svc(access_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
releasedir_1000_svc(releasedir_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
release_1000_svc(release_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

struct fgetattr_ret_IDL *
fgetattr_1000_svc(fgetattr_IDL *argp, struct svc_req *rqstp)
{
	static struct fgetattr_ret_IDL  result;

	/*
	 * insert server code here
	 */

	return &result;
}
