/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"
#include <stdio.h>

int *
getattr_10_svc(getattr_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
mkdir_10_svc(mkdir_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
rmdir_10_svc(rmdir_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
open_10_svc(open_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
read_10_svc(read_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
write_10_svc(write_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
opendir_10_svc(opendir_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
readdir_10_svc(readdir_IDL *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

void *
hellotest_10_svc(void *argp, struct svc_req *rqstp)
{
	static char * result;
	printf("*****************************\n")
	printf("HELLO!!!!!!!!!!!!!\n")
	printf("*****************************\n")
	return (void *) &result;
}
